version: "3.6"

services:
  homeworks-api:
    build: .
    container_name: homeworksApi
    env_file:
      - ./.env
    ports:
      - '8080:80'
    volumes:
      - ./app:/app/app
  
  homeworks-mongodb:
    image: mongo
    container_name: homeworksMongo
    ports:
      - '27017:27017'
    volumes:
      - 'projetdata:/data/db'

volumes:
  projetdata:
